const OPENAI_API_KEY = "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";
const OPENAI_MODEL = "gpt-3.5-turbo";
